// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SistemaAcademico.DAL;

#nullable disable

namespace SistemaAcademico.DAL.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260227175804_Inicial")]
    partial class Inicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SistemaAcademico.DAL.Models.Curso", b =>
                {
                    b.Property<int>("id_curso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_curso"));

                    b.Property<string>("nombreCurso")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("seccion")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id_curso");

                    b.ToTable("Cursos");
                });

            modelBuilder.Entity("SistemaAcademico.DAL.Models.Estudiante", b =>
                {
                    b.Property<int>("id_estudiante")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_estudiante"));

                    b.Property<string>("carnet")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nombreEstudiante")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id_estudiante");

                    b.ToTable("Estudiantes");
                });

            modelBuilder.Entity("SistemaAcademico.DAL.Models.Matricula", b =>
                {
                    b.Property<int>("id_matricula")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_matricula"));

                    b.Property<DateTime>("fechaInscripcion")
                        .HasColumnType("datetime2");

                    b.Property<int>("id_curso")
                        .HasColumnType("int");

                    b.Property<int>("id_estudiante")
                        .HasColumnType("int");

                    b.Property<int>("id_periodo")
                        .HasColumnType("int");

                    b.HasKey("id_matricula");

                    b.ToTable("Matriculas");
                });

            modelBuilder.Entity("SistemaAcademico.DAL.Models.Nota", b =>
                {
                    b.Property<int>("id_nota")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_nota"));

                    b.Property<string>("estado")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("fechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<int>("id_matricula")
                        .HasColumnType("int");

                    b.Property<decimal>("nota1")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("nota2")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("nota3")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("promedio")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("id_nota");

                    b.ToTable("Notas");
                });

            modelBuilder.Entity("SistemaAcademico.DAL.Models.Periodo", b =>
                {
                    b.Property<int>("id_periodo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_periodo"));

                    b.Property<string>("nombrePeriodo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id_periodo");

                    b.ToTable("Periodos");
                });
#pragma warning restore 612, 618
        }
    }
}
